---
- name: Collect home directories
  ansible.builtin.find:
    paths: /home
    file_type: directory
  register: home_directories

- name: Prepare bash prompt
  ansible.builtin.include_tasks: setup-Debian.yml
  when: ansible_os_family == "Debian"

- name: Prepare bash prompt
  ansible.builtin.include_tasks: setup-RedHat.yml
  when: ansible_os_family == "RedHat"
